version: '3'

services:
  redis:
    hostname: redis-host
    image: redis

  db:
    image: postgres:9.6.2-alpine
    environment:
        POSTGRES_USER: api_user
        POSTGRES_DB: reports_v2
        POSTGRES_PASSWORD: incode2015
        POSTGRES_HOST: db

    ports:
      - "5432:5432"
  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db